# Generated by Django 4.2.7 on 2024-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_options_post_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique_for_date="created_at"),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique_for_date="created_at"),
        ),
    ]
